# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: RyanMarinoff ISW-Prism Site
email: ryan.marinoff@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Within this site I will describe the process I used to create the ISW-Prism application
  and this site. I am learning everything on my own.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ryan_marinoff
github_username:  RyanMarinoff
repository: RyanMarinoff/ISW-Prism.github.io
# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
